[project]
name = "xotplot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "XotEmBotZ", email = "xotembotzop@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cartopy>=0.26.0",
    "cfgrib>=0.9.15.1",
    "dask>=2026.8.0",
    "eccodes>=2.49.0",
    "ecmwflibs>=0.7.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "pyqt6>=6.11.0",
    "xarray>=2026.9.0",
]

[project.scripts]
xotplot = "xotplot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
